spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://test20-db.9ny.me:3306/nuanyou20?useUnicode=true&characterEncoding=UTF-8
    username: nuanyou20
    password: 1qaz2wsxE
    test-on-borrow: true
    validation-query: select 1
#  开发
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://rdsw9r566jxer973wqi2.mysql.rds.aliyuncs.com:3306/nuanyou20?useUnicode=true&characterEncoding=UTF-8
#    username: dev
#    password: 1qaz2wsxE
#    test-on-borrow: true
#    validation-query: select 1


  mail:
    host: smtp.126.com
    username: zarabin@126.com
    password: aa529437740
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none

  http:
    multipart:
      max-file-size: 9Mb
      max-request-size: 20Mb

  velocity:
    charset: utf-8
    resource-loader-path: classpath:/templates/
    suffix: .vm
    toolbox-config-location: /velocity_toolbox.xml
    prefix:
    allow-request-override: false
    check-template-location: false

server:
  port: 8085
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/accesslog/

logging:
  config: classpath:logback-dev.xml

oss:
  bucketName: nuanyou-image
  domain: http://img.91nuanyou.com
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: OgdPMXR4cLyeIxEW
  secretAccessKey: zgSa3pBpQEo4EPQt1sVBF4U66QJZ21

#s3:
  #bucketName: dev.img.91nuanyou.com
  #domain: http://dev.img.91nuanyou.com
  #region: us-east-1
  #accessKey: AKIAJODFEQRC67I5MMTA
  #secretKey: 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
  #krCodeMainImgPath: barCodeImg/krCodeMainImg.jpg
  #thCodeMainImgPath: barCodeImg/thCodeMainImg.jpg
  #jpCodeMainImgPath: barCodeImg/jpCodeMainImg.jpg
  #geCodeMainImgPath: barCodeImg/geCodeMainImg.jpg
  #enCodeMainImgPath: barCodeImg/enCodeMainImg.jpg

s3:
  bucketName: nuanyou-resource-test
  domain: https://s3-ap-northeast-2.amazonaws.com
  region: ap-northeast-2
  accessKey: AKIAJUY7DPOSAJFGF6NA
  secretKey: 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
  barCodeMainImgPath: barCodeMainImg.jpg
  krCodeMainImgPath: barCodeImg/krCodeMainImg.jpg
  thCodeMainImgPath: barCodeImg/thCodeMainImg.jpg
  jpCodeMainImgPath: barCodeImg/jpCodeMainImg.jpg
  geCodeMainImgPath: barCodeImg/geCodeMainImg.jpg
  enCodeMainImgPath: barCodeImg/enCodeMainImg.jpg




nuanyou-host: http://testh5.91nuanyou.com
withdrawurl: http://testuser.api.91nuanyou.com

nuanyou-api: http://127.0.0.1:8081
#nuanyou-api: https://testapi30.91nuanyou.com


upload:
  s3server: https://kr.file.91nuanyou.com
elasticsearch:
  host: search-nyesearch-cgkyq332tvpvbi7q4n7nv4o5pe.ap-northeast-2.es.amazonaws.com
  index: test-cms-operation

AWS:
  region: ap-northeast-2
  sns:
    topic:
      refund: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refund
      refundSuccess: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refundSuccess
      refundFail: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refundFail

sso:
  urlPatterns: /*
  urlExcludePattern: ^/test|^/dist/.*|^/favicon.*|/|^/logout
  loginUrl: https://testuser.api.91nuanyou.com/oauth/corp
  reLogin: false
  serverName: http://127.0.0.1:8085
  validateCodeUrl: https://testuser.api.91nuanyou.com/corp/oauth/access_token
  stateExpiredInMilliSeconds: 120000


contractService: http://127.0.0.1:8200
accountService: http://127.0.0.1:8086
orderService: http://172.16.0.230:8017

paymentRecord:
  service-address: http://test.payment.91nuanyou.com
  pattern-url: /paymentOrderRecord/*
  waiting-time: 5

numberbind:
    domain: https://9ny.me/api/

autoHandleRefund:
  url: http://test.payment.91nuanyou.com/order/refund

crm:
  sg:
    domain: https://test.crm.91nuanyou.com
  kr:
    domain: https://test.crm.91nuanyou.com
  authKey: 123456

7moor:
  domain: http://apis.7moor.com
  id: N00000016592
  secret: 71d88120-e3a6-11e7-a47c-9516d082d912
  version: 201712140004