spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://nuanyou20db.91nuanyou.com:3306/nuanyou20?useUnicode=true&characterEncoding=UTF-8
    username: nuanyou20
    password: 1qaz2wsxE
    test-on-borrow: true
    validation-query: select 1

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none

  http:
    multipart:
      max-file-size: 9Mb
      max-request-size: 20Mb

  velocity:
    charset: utf-8
    resource-loader-path: classpath:/templates/
    suffix: .vm
    toolbox-config-location: /velocity_toolbox.xml
    prefix:
    allow-request-override: false
    check-template-location: false

server:
  port: 8085
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/accesslog/

aliyun:
 oss:
  access-key-id: OgdPMXR4cLyeIxEW
  secret-access-key: zgSa3pBpQEo4EPQt1sVBF4U66QJZ21
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
 nuanyou:
  image-server: https://img.91nuanyou.com
  bucketname: nuanyou-image
  cms-basepath: cms
  fake-image-server: http://image.hellodfs.com/nuanyou20opt
  fakeuser-basepath: nuanyou20opt/user
  fakercomment-basepath: nuanyou20opt/comment

nuanyou-host: http://testh5.91nuanyou.com
withdrawurl: http://testuser.api.91nuanyou.com
nuanyou-api: http://127.0.0.1:8081

upload:
  s3server: https://kr.file.91nuanyou.com



AWS:
  sns:
    topic:
      refund: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refund
      refundSuccess: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refundSuccess
      refundFail: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refundFail


sso:
  urlPatterns: /*
  urlExcludePattern: ^/test|^/dist/.*|^/favicon.*
  loginUrl: https://testuser.api.91nuanyou.com/oauth/corp
  reLogin: false
  serverName: http://172.16.0.104:8085
  validateCodeUrl: https://testuser.api.91nuanyou.com/corp/oauth/access_token
  stateExpiredInMilliSeconds: 120000


contractService: http://172.16.0.195:8200


accountService: http://127.0.0.1:8086



merchantSettlement:
  default:
    daytype: 1
    startprice: 1
