spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rdsw9r566jxer973wqi2.mysql.rds.aliyuncs.com:3306/nuanyou20?useUnicode=true&characterEncoding=UTF-8
    username: dev
    password: 1qaz2wsxE
    test-on-borrow: true
    validation-query: select 1

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none

  http:
    multipart:
      max-file-size: 9Mb
      max-request-size: 20Mb

  velocity:
    charset: utf-8
    resource-loader-path: classpath:/templates/
    suffix: .vm
    toolbox-config-location: /velocity_toolbox.xml
    prefix:
    allow-request-override: false
    check-template-location: false

server:
  port: 8085
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/accesslog/

logging:
  config: classpath:logback-dev.xml

oss:
  bucketName: nuanyou-image
  domain: http://img.91nuanyou.com
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: OgdPMXR4cLyeIxEW
  secretAccessKey: zgSa3pBpQEo4EPQt1sVBF4U66QJZ21

s3:
  bucketName: nuanyou-file-prod-ap-northeast-2
  domain: https://kr.file.91nuanyou.com
  region: ap-northeast-2

nuanyou-host: http://testh5.91nuanyou.com
withdrawurl: http://testuser.api.91nuanyou.com
nuanyou-api: http://127.0.0.1:8081

upload:
  s3server: https://kr.file.91nuanyou.com
elasticsearch:
  host: search-nyesearch-cgkyq332tvpvbi7q4n7nv4o5pe.ap-northeast-2.es.amazonaws.com
  index: test-cms-operation

AWS:
  region: ap-northeast-2
  sns:
    topic:
      refund: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refund
      refundSuccess: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refundSuccess
      refundFail: arn:aws:sns:ap-northeast-2:904656167085:test-ny-v3-refundFail

sso:
  urlPatterns: /*
  urlExcludePattern: ^/test|^/dist/.*|^/favicon.*|/
  loginUrl: https://testuser.api.91nuanyou.com/oauth/corp
  reLogin: false
  serverName: http://127.0.0.1:8085
  validateCodeUrl: https://testuser.api.91nuanyou.com/corp/oauth/access_token
  stateExpiredInMilliSeconds: 120000
  needAutoLogOut: true


contractService: http://127.0.0.1:8200
accountService: http://127.0.0.1:8086


paymentRecord:
  service-address: http://test.payment.91nuanyou.com
  pattern-url: /paymentOrderRecord/*
  waiting-time: 5

numberbind:
    domain: https://9ny.me/api/