/*
 * Copyright 2007 The JA-SIG Collaborative. All rights reserved. See license
 * distributed with this file and available online at
 * http://www.ja-sig.org/products/cas/overview/license/
 */
package com.nuanyou.sso.client.ticket;

/**
 */
public interface StateTicket extends Ticket {

    /** Prefix generally applied to unique ids generated by UniqueIdGenenerator. */
    String PREFIX = "STATE";


}
